//Export constants for entities providers
//Auth
export const AUTH_REPOSITORY = 'AUTH_REPOSITORY'
export const USER_REPOSITORY = 'USER_REPOSITORY'
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY'
export const ROLES_USER_REPOSITORY = 'ROLES_USER_REPOSITORY'

//Profile
export const PROFILE_REPOSITORY = 'PROFILE_REPOSITORY'

//Products
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY'
export const ORDER_REPOSITORY = 'ORDER_REPOSITORY'
export const INVENTORY_REPOSITORY = 'INVENTORY_REPOSITORY'
export const INVENTORY_TRANSACTION_REPOSITORY = 'INVENTORY_TRANSACTION_REPOSITORY'
